name: Create release
on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependency
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 648ACFD622F3D138
          sudo add-apt-repository 'deb http://deb.debian.org/debian experimental main'
          sudo apt update
          sudo apt-get -t experimental -y install capnproto=0.8.0-1
          sudo apt-get -y install opencc inkscape

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Set keystore
        run: |
          openssl aes-256-cbc -K $encrypted_26e1bb6b6b4a_key -iv $encrypted_26e1bb6b6b4a_iv -in keystore.tar.enc -out keystore.tar -d
          tar xvf keystore.tar
          ls -la keystore .

      - name: Archive rimerc
        run: make release

      - name: Build changelog
        id: release_log
        run: |
          log=$(./script/changelog.sh)
          # multiline
          log="${log//'%'/'%25'}"
          log="${log//$'\n'/'%0A'}"
          log="${log//$'\r'/'%0D'}"

          echo "::set-output name=changelog::$log"

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "app/build/outputs/apk/*.apk"
          draft: true
          body: |
            ${{ steps.release_log.outputs.changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}
